name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Test
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-node/issues/899#issuecomment-1828798029
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Check Cache
        uses: actions/cache@v3
        id: yarnCache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.yarnCache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4
      - run: |
          echo "BASE: ${{ steps.setSHAs.outputs.base }}"
          echo "HEAD: ${{ steps.setSHAs.outputs.head }}"

      - name: Build
        run: yarn build:all

      - name: Test
        # 추가할 `scripts`는 여기에.
        run: yarn nx affected -t test cy:component --configuration=ci

      - name: E2E
        run: yarn cy:e2e

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: 'Test Results'
          files: |
            reports/**/*.vitest.xml
            reports/**/*.cy.xml
            reports/**/*.e2e.xml
